
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
